<?php

$database = array(
	"male_names" => array(
		'Jan',
		'Stanisław',
		'Andrzej',
		'Józef',
		'Tadeusz',
		'Jerzy',
		'Zbigniew',
		'Krzysztof',
		'Henryk',
		'Ryszard',
		'Kazimierz',
		'Marek',
		'Marian',
		'Piotr',
		'Janusz',
		'Władysław',
		'Adam',
		'Wiesław',
		'Zdzisław',
		'Edward',
		'Mieczysław',
		'Roman',
		'Mirosław',
		'Grzegorz',
		'Czesław',
		'Dariusz',
		'Wojciech',
		'Jacek',
		'Eugeniusz',
		'Tomasz',
		'Stefan',
		'Zygmunt',
		'Leszek',
		'Bogdan',
		'Antoni',
		'Paweł',
		'Franciszek',
		'Sławomir',
		'Waldemar',
		'Jarosław',
		'Robert',
		'Mariusz',
		'Włodzimierz',
		'Michał',
		'Zenon',
		'Bogusław',
		'Witold',
		'Aleksander',
		'Bronisław',
		'Wacław',
		'Bolesław',
		'Ireneusz',
		'Maciej',
		'Artur',
		'Edmund',
		'Marcin',
		'Lech',
		'Karol',
		'Rafał',
		'Arkadiusz',
		'Leon',
		'Sylwester',
		'Lucjan',
		'Julian',
		'Wiktor',
		'Romuald',
		'Bernard',
		'Ludwik',
		'Feliks',
		'Alfred',
		'Alojzy',
		'Przemysław',
		'Cezary',
		'Daniel',
		'Mikołaj',
		'Ignacy',
		'Lesław',
		'Radosław',
		'Konrad',
		'Bogumił',
		'Szczepan',
		'Gerard',
		'Hieronim',
		'Krystian',
		'Leonard',
		'Wincenty',
		'Benedykt',
		'Hubert',
		'Sebastian',
		'Norbert',
		'Adolf',
		'Łukasz',
		'Emil',
		'Teodor',
		'Rudolf',
		'Joachim',
		'Jakub',
		'Walenty',
		'Alfons',
		'Damian',
		'Rajmund',
		'Szymon',
		'Zygfryd',
		'Leopold',
		'Remigiusz',
		'Florian',
		'Konstanty',
		'Augustyn',
		'Albin',
		'Bohdan',
		'Dominik',
		'Gabriel',
		'Teofil',
		'Brunon',
		'Juliusz',
		'Walerian',
		'Bartłomiej',
		'Fryderyk',
		'Eryk',
		'Anatol',
		'Maksymilian',
		'Gustaw',
		'Aleksy',
		'Longin',
		'Bartosz',
		'Wilhelm',
		'Ferdynand',
		'Erwin',
		'Klemens',
		'Lechosław',
		'Ernest',
		'Seweryn',
		'Herbert',
		'Albert',
		'Błażej',
		'Izydor',
		'Dionizy',
		'Edwin',
		'Ginter',
		'Adrian',
		'Mateusz',
		'Walter',
		'Helmut',
		'Bazyli',
		'Marceli',
		'Sergiusz',
		'Bonifacy',
		'Werner',
		'Eligiusz',
		'Wawrzyniec',
		'Kamil',
		'Łucjan',
		'Olgierd',
		'Arnold',
		'Jacenty',
		'Dawid',
		'Ewald',
		'Manfred',
		'Emilian',
		'Klaudiusz',
		'Zbysław',
		'Igor',
		'Benon',
		'Jędrzej',
		'Wit',
		'Hilary',
		'Apolinary',
		'Fabian',
		'Zenobiusz',
		'Horst',
		'Gerhard',
		'Roland',
		'Euzebiusz',
		'Hipolit',
		'Filip',
		'Nikodem',
		'Miron',
		'January',
		'Kajetan'
	),
	
	"famale_names" => array(
		'Maria',
		'Krystyna',
		'Anna',
		'Barbara',
		'Teresa',
		'Elżbieta',
		'Janina',
		'Zofia',
		'Jadwiga',
		'Danuta',
		'Halina',
		'Irena',
		'Ewa',
		'Małgorzata',
		'Helena',
		'Grażyna',
		'Bożena',
		'Stanisława',
		'Jolanta',
		'Marianna',
		'Urszula',
		'Wanda',
		'Alicja',
		'Dorota',
		'Agnieszka',
		'Beata',
		'Katarzyna',
		'Joanna',
		'Wiesława',
		'Renata',
		'Iwona',
		'Genowefa',
		'Kazimiera',
		'Stefania',
		'Hanna',
		'Lucyna',
		'Józefa',
		'Alina',
		'Mirosława',
		'Aleksandra',
		'Władysława',
		'Henryka',
		'Czesława',
		'Lidia',
		'Regina',
		'Monika',
		'Magdalena',
		'Bogumiła',
		'Marta',
		'Marzena',
		'Leokadia',
		'Mariola',
		'Bronisława',
		'Aniela',
		'Bogusława',
		'Eugenia',
		'Izabela',
		'Cecylia',
		'Emilia',
		'Łucja',
		'Gabriela',
		'Sabina',
		'Zdzisława',
		'Agata',
		'Edyta',
		'Aneta',
		'Daniela',
		'Wioletta',
		'Sylwia',
		'Weronika',
		'Antonina',
		'Justyna',
		'Gertruda',
		'Mieczysława',
		'Franciszka',
		'Rozalia',
		'Zuzanna',
		'Natalia',
		'Celina',
		'Ilona',
		'Alfreda',
		'Wiktoria',
		'Olga',
		'Wacława',
		'Róża',
		'Karolina',
		'Bernadeta',
		'Julia',
		'Michalina',
		'Adela',
		'Ludwika',
		'Honorata',
		'Aldona',
		'Eleonora',
		'Violetta',
		'Wiktora',
		'Wodzisława'
	),

	"famale_surnames" => array(
		'Adamowicz',
		'Antosiewicz',
		'Bator',
		'Chmielewska',
		'Dunaj',
		'Filipiak',
		'Flis',
		'Jabłońska',
		'Kamińska',
		'Kos',
		'Kowalczyk',
		'Krynicka',
		'Leśniewska',
		'Lewandowska',
		'Lewińska',
		'Lubomirska',
		'Markowska',
		'Miłek',
		'Nowakowska',
		'Ostrowska',
		'Piasecka',
		'Pisarska',
		'Podgórska',
		'Polańska',
		'Różańska',
		'Skalska',
		'Stankiewicz',
		'Szafrańska',
		'Szymanowska',
		'Tomaszewska',
		'Tyszkiewicz',
		'Wysocka',
		'Zamojska',
		'Zielińska'
	),

	"male_surnames" => array(
		'Zając',
		'Pawłowski',
		'Michalski',
		'Król',
		'Wieczorek',
		'Jabłoński',
		'Wróbel',
		'Nowakowski',
		'Majewski',
		'Olszewski',
		'Stępień',
		'Malinowski',
		'Jaworski',
		'Adamczyk',
		'Dudek',
		'Nowicki',
		'Pawlak',
		'Górski',
		'Witkowski',
		'Walczak',
		'Sikora',
		'Baran',
		'Rutkowski',
		'Michalak',
		'Szewczyk',
		'Ostrowski',
		'Tomaszewski',
		'Pietrzak'
	),

	"identification_card_type" => array(
		1 => "Dowód osobisty",
		2 => "Paszport"
	),

	"tax_offices_PL" => array(
		1 => 'Izba Skarbowa we Wrocławiu',
		2 => 'Dolnośląski Urząd Skarbowy we Wrocławiu',
		3 => 'Urząd Skarbowy w Bolesławcu',
		4 => 'Urząd Skarbowy w Bystrzycy Kłodzkiej',
		5 => 'Urząd Skarbowy w  Dzierżoniowie',
		6 => 'Urząd Skarbowy w Głogowie',
		7 => 'Urząd skarbowy w Górze',
		8 => 'Urząd Skarbowy w Jaworze',
		9 => 'Urząd Skarbowy w  Jeleniej Górze',
		10 => 'Urząd Skarbowy w Kamiennej Górze',
		11 => 'Urząd Skarbowy w  Kłodzku',
		12 => 'Urząd Skarbowy w Legnicy',
		13 => 'Urząd Skarbowy w Lubaniu',
		14 => 'Urząd Skarbowy w Lubinie',
		15 => 'Urząd Skarbowy w Lwówku Śląskim',
		16 => 'Urząd Skarbowy w Miliczu',
		17 => 'Urząd Skarbowy w  Nowej Rudzie',
		18 => 'Urząd Skarbowy w Oleśnicy',
		19 => 'Urząd Skarbowy w  w Oławie',
		20 => 'Urząd Skarbowy w Polkowicach',
		21 => 'Urząd Skarbowy w Strzelinie',
		22 => 'Urząd Skarbowy w Środzie Śląskiej',
		23 => 'Urząd Skarbowy w Świdnicy',
		24 => 'Urząd Skarbowy w Trzebnicy',
		25 => 'Urząd Skarbowy w  Wałbrzychu',
		26 => 'Urząd Skarbowy w  Wołowie',
		27 => 'Urząd Skarbowy Wrocław - Fabryczna',
		28 => 'Urząd Skarbowy Wrocław - Krzyki',
		29 => 'Urząd Skarbowy Wrocław - Psie Pole',
		30 => 'Urząd Skarbowy Wrocław - Stare Miasto',
		31 => 'Urząd Skarbowy Wrocław - Śródmieście',
		32 => 'Pierwszy Urząd Skarbowy we Wrocławiu',
		33 => 'Urząd Skarbowy w  Ząbkowicach Śląskich',
		34 => 'Urząd Skarbowy w Zgorzelcu',
		35 => 'Urząd Skarbowy w Złotoryi',
		36 => 'Izba Skarbowa w Bydgoszczy',
		37 => 'Biuro Krajowej Informacji Podatkowej w Toruniu',
		38 => 'Kujawsko-Pomorski Urząd Skarbowy w  Bydgoszczy',
		39 => 'Urząd Skarbowy w Aleksandrowie Kujawskim',
		40 => 'Urząd Skarbowy w Brodnicy',
		41 => 'Pierwszy Urząd Skarbowy w Bydgoszczy',
		42 => 'Drugi Urząd Skarbowy w  Bydgoszczy',
		43 => 'Trzeci Urząd Skarbowy w Bydgoszczy',
		44 => 'Urząd Skarbowy w  Chełmnie',
		45 => 'Urząd Skarbowy w Golubiu-Dobrzyniu',
		46 => 'Urząd Skarbowy w  Grudziądzu',
		47 => 'Urząd Skarbowy w  Inowrocławiu',
		48 => 'Urząd Skarbowy w  Lipnie',
		49 => 'Urząd Skarbowy w Mogilnie',
		50 => 'Urząd Skarbowy w Nakle nad Notecią',
		51 => 'Urząd Skarbowy w Radziejowie',
		52 => 'Urząd Skarbowy w  Rypinie',
		53 => 'Urząd Skarbowy w Sępólnie Krajeńskim',
		54 => 'Urząd Skarbowy w Świeciu',
		55 => 'Pierwszy Urząd Skarbowy w Toruniu',
		56 => 'Drugi Urząd Skarbowy w Toruniu',
		57 => 'Urząd Skarbowy w  Tucholi',
		58 => 'Urząd Skarbowy w  Wąbrzeźnie',
		59 => 'Urząd Skarbowy we Włocławku',
		60 => 'Urząd Skarbowy w Żninie',
		61 => 'Izba Skarbowa w Lublinie',
		62 => 'Wydział Orzecznictwa i Logistyki IS w Lublinie',
		63 => 'Lubelski Urząd Skarbowy w Lublinie',
		64 => 'Urząd Skarbowy w  Białej Podlaskiej',
		65 => 'Urząd Skarbowy w Biłgoraju',
		66 => 'Urząd Skarbowy w Chełmie',
		67 => 'Urząd Skarbowy w Hrubieszowie',
		68 => 'Urząd Skarbowy w Janowie Lubelskim',
		69 => 'Urząd Skarbowy w Krasnymstawie',
		70 => 'Urząd Skarbowy w Kraśniku',
		71 => 'Urząd Skarbowy w Lubartowie',
		72 => 'Pierwszy Urząd Skarbowy w Lublinie',
		73 => 'Drugi Urząd Skarbowy w Lublinie',
		74 => 'Trzeci Urząd Skarbowy w Lublinie',
		75 => 'Urząd Skarbowy w Łęcznej',
		76 => 'Urząd Skarbowy w Łukowie',
		77 => 'Urząd Skarbowy w Opolu Lubelskim',
		78 => 'Urząd Skarbowy w Parczewie',
		79 => 'Urząd Skarbowy w Puławach',
		80 => 'Urząd Skarbowy w Radzyniu Podl.',
		81 => 'Urząd Skarbowy w Rykach',
		82 => 'Urząd Skarbowy w Tomaszowie Lubelskim',
		83 => 'Urząd Skarbowy we Włodawie',
		84 => 'Urząd Skarbowy w Zamościu',
		85 => 'Izba  Skarbowa w Zielonej Górze',
		86 => 'Lubuski Urząd Skarbowy w Zielonej Górze',
		87 => 'Urząd Skarbowy w Drezdenku',
		88 => 'Urząd Skarbowy w Gorzowie Wlkp.',
		89 => 'Urząd Skarbowy w Krośnie Odrz.',
		90 => 'Urząd Skarbowy w Miedzyrzeczu',
		91 => 'Urząd Skarbowy w Nowej Soli',
		92 => 'Urząd Skarbowy w Słubicach',
		93 => 'Urząd Skarbowy w Sulęcinie',
		94 => 'Urząd Skarbowy w Świebodzinie',
		95 => 'Urząd Skarbowy we  Wschowie',
		96 => 'Pierwszy Urząd Skarbowy w Zielonej Górze',
		97 => 'Drugi Urząd Skarbowy w Zielonej Górze',
		98 => 'Urząd Skarbowy w Źaganiu',
		99 => 'Urząd Skarbowy w Żarach',
		100 => 'Izba Skarbowa w Łodzi',
		101 => 'Biuro Krajowej Informacji Podatkowej w Piotrkowie Trybunalskim',
		102 => 'Łódzki Urząd Skarbowy',
		103 => 'Urząd Skarbowy w Bełchatowie',
		104 => 'Urząd Skarbowy w Brzezinach',
		105 => 'Urząd Skarbowy w Głownie',
		106 => 'Urząd Skarbowy w Kutnie',
		107 => 'Urząd Skarbowy w Łasku',
		108 => 'Urząd Skarbowy w Łęczycy',
		109 => 'Urząd Skarbowy w Łowiczu',
		110 => 'Pierwszy Urząd Skarbowy Łódź- Bałuty',
		111 => 'Drugi Urząd Skarbowy Łódź-Bałuty',
		112 => 'Pierwszy Urząd Skarbowy Łódź- Górna',
		113 => 'Drugi Urząd Skarbowy Łódź-Górna',
		114 => 'Urząd Skarbowy Łódź-Polesie',
		115 => 'Urząd Skarbowy Łódź-Śródmieście',
		116 => 'Urząd Skarbowy Łódź-Widzew',
		117 => 'Urząd Skarbowy w Opocznie',
		118 => 'Urząd Skarbowy w Pabianicach',
		119 => 'Urząd Skarbowy w Pajęcznie',
		120 => 'Urząd Skarbowy w Piotrkowie Trybunalskim',
		121 => 'Urząd Skarbowy w Poddębicach',
		122 => 'Urząd Skarbowy w Radomsku',
		123 => 'Urząd Skarbowy w Rawie Mazowieckiej',
		124 => 'Urząd Skarbowy w Sieradzu',
		125 => 'Urząd Skarbowy w Skierniewicach',
		126 => 'Urząd Skarbowy w Tomaszowie Mazowieckim',
		127 => 'Urząd Skarbowy w Wieluniu',
		128 => 'Urząd Skarbowy w Wieruszowie',
		129 => 'Urząd Skarbowy w Zduńskiej Woli',
		130 => 'Urząd Skarbowy w Zgierzu',
		131 => 'Izba Skarbowa w Krakowie',
		132 => 'Małopolski Urząd Skarbowy',
		133 => 'Urząd Skarbowy w Bochni',
		134 => 'Urząd Skarbowy w Brzesku',
		135 => 'Urząd Skarbowy w Chrzanowie',
		136 => 'Urząd Skarbowy w Dąbrowie Tarnowskiej',
		137 => 'Urząd Skarbowy w Gorlicach',
		138 => 'Pierwszy Urząd Skarbowy Kraków',
		139 => 'Drugi Urząd Skarbowy Kraków',
		140 => 'Urząd Skarbowy Kraków-Krowodrza',
		141 => 'Urząd Skarbowy Kraków-Nowa Huta',
		142 => 'Urząd Skarbowy Kraków-Podgórze',
		143 => 'Urząd Skarbowy Kraków-Prądnik',
		144 => 'Urząd Skarbowy Kraków-Stare Miasto',
		145 => 'Urząd Skarbowy Kraków-Śródmieście',
		146 => 'Urząd Skarbowy w Limanowej',
		147 => 'Urząd Skarbowy w Miechowie',
		148 => 'Urząd Skarbowy w Myślenicach',
		149 => 'Urząd Skarbowy w Nowym Sączu',
		150 => 'Urząd Skarbowy w Nowym Targu',
		151 => 'Urząd Skarbowy w Olkuszu',
		152 => 'Urząd Skarbowy w Oświęcimiu',
		153 => 'Urząd Skarbowy w Proszowicach',
		154 => 'Urząd Skarbowy w Suchej Beskidzkiej',
		155 => 'Pierwszy Urząd Skarbowy w Tarnowie',
		156 => 'Drugi Urząd Skarbowy w Tarnowie',
		157 => 'Urząd Skarbowy w Wadowicach',
		158 => 'Urząd Skarbowy w Wieliczce',
		159 => 'Urząd Skarbowy w Zakopanem',
		160 => 'Izba Skarbowa w Warszawie',
		161 => 'Biuro Krajowej Informacji Podatkowej w Płocku',
		162 => 'Pierwszy Mazowiecki Urząd Skarbowy',
		163 => 'Drugi Mazowiecki Urząd Skarbowy',
		164 => 'Trzeci Mazowiecki Urząd Skarbowy',
		165 => 'Urząd Skarbowy w Białobrzegach',
		166 => 'Urząd Skarbowy w Ciechanowie',
		167 => 'Urząd Skarbowy w Garwolinie',
		168 => 'Urząd Skarbowy w Gostyninie',
		169 => 'Urząd Skarbowy w Grodzisku Mazowieckim',
		170 => 'Urząd Skarbowy w Grójcu',
		171 => 'Urząd Skarbowy w Kozienicach',
		172 => 'Urząd Skarbowy w Legionowie',
		173 => 'Urząd Skarbowy w Lipsku',
		174 => 'Urząd Skarbowy w Łosicach',
		175 => 'Urząd Skarbowy w Makowie Mazowieckim',
		176 => 'Urząd Skarbowy w Mińsku Mazowieckim',
		177 => 'Urząd Skarbowy w Mławie',
		178 => 'Urząd Skarbowy w Nowym Dworze Mazowieckim',
		179 => 'Urząd Skarbowy w Ostrołęce',
		180 => 'Urząd Skarbowy w Ostrowi Mazowieckiej',
		181 => 'Urząd Skarbowy w Otwocku',
		182 => 'Urząd Skarbowy w Piasecznie',
		183 => 'Urząd Skarbowy w Płocku',
		184 => 'Urząd Skarbowy w Płońsku',
		185 => 'Urząd Skarbowy w Pruszkowie',
		186 => 'Urząd Skarbowy w Przasnyszu',
		187 => 'Urząd Skarbowy w Przysusze',
		188 => 'Urząd Skarbowy w Pułtusku',
		189 => 'I Urząd Skarbowy w Radomiu',
		190 => 'II Urząd Skarbowy w Radomiu',
		191 => 'Urząd Skarbowy w Siedlcach',
		192 => 'Urząd Skarbowy w Sierpcu',
		193 => 'Urząd Skarbowy w Sochaczewie',
		194 => 'Urząd Skarbowy w Sokołowie Podlaskim',
		195 => 'Urząd Skarbowy w Szydłowcu',
		196 => 'Urząd Skarbowy Warszawa-Bemowo',
		197 => 'Urząd Skarbowy Warszawa-Bielany',
		198 => 'Urząd Skarbowy Warszawa-Mokotów',
		199 => 'Urząd Skarbowy Warszawa-Praga',
		200 => 'Pierwszy Urząd Skarbowy Warszawa-Śródmieście',
		201 => 'Drugi Urząd Skarbowy Warszawa-Śródmieście',
		202 => 'Trzeci Urząd Skarbowy Warszawa-Śródmieście',
		203 => 'Urząd Skarbowy Warszawa-Targówek',
		204 => 'Urząd Skarbowy Warszawa-Ursynów',
		205 => 'Urząd Skarbowy Warszawa-Wawer',
		206 => 'Urząd Skarbowy Warszawa-Wola',
		207 => 'Urząd Skarbowy w Węgrowie',
		208 => 'Urząd Skarbowy w Wołominie',
		209 => 'Urząd Skarbowy w Wyszkowie',
		210 => 'Urząd Skarbowy w Zwoleniu',
		211 => 'Urząd Skarbowy w Żurominie',
		212 => 'Urząd Skarbowy w Żyrardowie',
		213 => 'Izba Skarbowa w Opolu',
		214 => 'Opolski Urząd Skarbowy w Opolu',
		215 => 'Urząd Skarbowy w  Brzegu',
		216 => 'Urząd Skarbowy w Głubczycach',
		217 => 'Urząd Skarbowy w Kędzierzynie-Koźlu',
		218 => 'Urząd Skarbowy w Kluczborku',
		219 => 'Urząd Skarbowy w Krapkowicach',
		220 => 'Urząd Skarbowy w Namysłowie',
		221 => 'Urząd Skarbowy w Nysie',
		222 => 'Urząd Skarbowy w Oleśnie',
		223 => 'Pierwszy Urząd Skarbowy w Opolu',
		224 => 'Drugi Urząd Skarbowy w Opolu',
		225 => 'Urząd Skarbowy w Prudniku',
		226 => 'Urząd Skarbowy w Strzelcach Opolskich',
		227 => 'Izba Skarbowa w Rzeszowie',
		228 => 'Podkarpacki Urząd Skarbowy w Rzeszowie',
		229 => 'Urząd Skarbowy w  Brzozowie',
		230 => 'Urząd Skarbowy w Dębicy',
		231 => 'Urząd Skarbowy w Jarosławiu',
		232 => 'Urząd Skarbowy w Jaśle',
		233 => 'Urząd Skarbowy w  Kolbuszowej',
		234 => 'Urząd Skarbowy w Krośnie',
		235 => 'Urząd Skarbowy w  Lesku',
		236 => 'Urząd Skarbowy w  Leżajsku',
		237 => 'Urząd Skarbowy w Lubaczowie',
		238 => 'Urząd Skarbowy w Łańcucie',
		239 => 'Urząd Skarbowy w Mielcu',
		240 => 'Urząd Skarbowy w Nisku',
		241 => 'Urząd Skarbowy w Przemyślu',
		242 => 'Urząd Skarbowy w  Przeworsku',
		243 => 'Urząd Skarbowy w  Ropczycach',
		244 => 'Pierwszy Urząd Skarbowy w  Rzeszowie',
		245 => 'Drugi Urząd Skarbowy w Rzeszowie',
		246 => 'Urząd Skarbowy w  Sanoku',
		247 => 'Urząd Skarbowy w  Stalowej Woli',
		248 => 'Urząd Skarbowy w  Strzyżowie',
		249 => 'Urząd Skarbowy w Tarnobrzegu',
		250 => 'Urząd Skarbowy w  Ustrzykach Dolnych',
		251 => 'Izba Skarbowa w Białymstoku',
		252 => 'Podlaski Urząd Skarbowy',
		253 => 'Urząd Skarbowy w Augustowie',
		254 => 'Pierwszy Urząd Skarbowy w Białymstoku',
		255 => 'Drugi Urząd Skarbowy w Białymstoku',
		256 => 'Urząd Skarbowy w Bielsku Podlaskim',
		257 => 'Urząd Skarbowy w Grajewie',
		258 => 'Urząd Skarbowy w Hajnówce',
		259 => 'Urząd Skarbowy w Kolnie',
		260 => 'Urząd Skarbowy w Łomży',
		261 => 'Urząd Skarbowy w Mońkach',
		262 => 'Urząd Skarbowy w Siemiatyczach',
		263 => 'Urząd Skarbowy w Sokółce',
		264 => 'Urząd Skarbowy w Suwałkach',
		265 => 'Urząd Skarbowy w Wysokiem Mazowieckiem',
		266 => 'Urząd Skarbowy w Zambrowie',
		267 => 'Izba Skarbowa w Gdańsku',
		268 => 'Pomorski Urząd Skarbowy w Gdańsku',
		269 => 'Urząd Skarbowy w Bytowie',
		270 => 'Urząd Skarbowy w Chojnicach',
		271 => 'Urząd Skarbowy w Człuchowie',
		272 => 'Pierwszy Urząd Skarbowy w Gdańsku',
		273 => 'Drugi Urząd Skarbowy w Gdańsku',
		274 => 'Trzeci Urząd Skarbowy w Gdańsku',
		275 => 'Pierwszy Urząd Skarbowy w Gdyni',
		276 => 'Drugi Urząd Skarbowy w Gdyni',
		277 => 'Urząd Skarbowy w Kartuzach',
		278 => 'Urząd Skarbowy w Kościerzynie',
		279 => 'Urząd Skarbowy w Kwidzynie',
		280 => 'Urząd Skarbowy w Lęborku',
		281 => 'Urząd Skarbowy w Malborku',
		282 => 'Urząd Skarbowy w Pruszczu Gdańskim',
		283 => 'Urząd Skarbowy w Pucku',
		284 => 'Urząd Skarbowy w Słupsku',
		285 => 'Urząd Skarbowy w Sopocie',
		286 => 'Urząd Skarbowy w Starogardzie Gdańskim',
		287 => 'Urząd Skarbowy w Tczewie',
		288 => 'Urząd Skarbowy w Wejherowie',
		289 => 'Izba Skarbowa w Katowicach',
		290 => 'Biuro Krajowej Informacji Podatkowej w Bielsku- Białej',
		291 => 'Pierwszy Śląski Urząd Skarbowy w Sosnowcu',
		292 => 'Drugi Śląski Urząd Skarbowy',
		293 => 'w Bielsku- Białej',
		294 => 'Urząd Skarbowy w Będzinie',
		295 => 'Pierwszy Urząd Skarbowy w Bielsku- Białej',
		296 => 'Drugi Urząd Skarbowy w Bielsku -Białej',
		297 => 'Urząd Skarbowy w Bytomiu',
		298 => 'Urząd Skarbowy w Chorzowie',
		299 => 'Urząd Skarbowy w Cieszynie',
		300 => 'Urząd Skarbowy w Czechowicach- Dziedzicach',
		301 => 'Pierwszy Urząd Skarbowy w Częstochowie',
		302 => 'Drugi Urząd Skarbowy w Częstochowie',
		303 => 'Urząd Skarbowy w Dąbrowie Górniczej',
		304 => 'Pierwszy Urząd Skarbowy w Gliwicach',
		305 => 'Drugi Urząd Skarbowy w Gliwicach',
		306 => 'Urząd Skarbowy w Jastrzębiu- Zdrój',
		307 => 'Urząd Skarbowy w Jaworznie',
		308 => 'Pierwszy Urząd Skarbowy w Katowicach',
		309 => 'Drugi Urząd Skarbowy w Katowicach',
		310 => 'Urząd Skarbowy w Kłobucku',
		311 => 'Urząd Skarbowy w Lublińcu',
		312 => 'Urząd Skarbowy w Mikołowie',
		313 => 'Urząd Skarbowy w Mysłowicach',
		314 => 'Urząd Skarbowy w Myszkowie',
		315 => 'Urząd Skarbowy w Piekarach Śląskich',
		316 => 'Urząd Skarbowy w Pszczynie',
		317 => 'Urząd Skarbowy w Raciborzu',
		318 => 'Urząd Skarbowy w Rudzie Śląskiej',
		319 => 'Urząd Skarbowy w Rybniku',
		320 => 'Urząd Skarbowy w Siemianowicach Śląskich',
		321 => 'Urząd Skarbowy w Sosnowcu',
		322 => 'Urząd Skarbowy w Tarnowskich Górach',
		323 => 'Urząd Skarbowy w Tychach',
		324 => 'Urząd Skarbowy w Wodzisławiu Śląskim',
		325 => 'Urząd Skarbowy w Zabrzu',
		326 => 'Urząd Skarbowy w Zawierciu',
		327 => 'Urząd Skarbowy w Żorach',
		328 => 'Urząd Skarbowy w Żywcu',
		329 => 'Izba Skarbowa w Kielcach',
		330 => 'Świętokrzyski Urząd Skarbowy w Kielcach',
		331 => 'Urząd Skarbowy w Busku Zdroju',
		332 => 'Urząd Skarbowy w Jędrzejowie',
		333 => 'Pierwszy Urząd Skarbowy w Kielcach',
		334 => 'Drugi Urząd Skarbowy w Kielcach',
		335 => 'Urząd Skarbowy w Kazimierzy Wielkiej',
		336 => 'Urząd Skarbowy w Końskich',
		337 => 'Urząd Skarbowy w Opatowie',
		338 => 'Urząd Skarbowy w Ostrowcu Świętokrzyskim',
		339 => 'Urząd Skarbowy w Pińczowie',
		340 => 'Urząd Skarbowy w Sandomierzu',
		341 => 'Urząd Skarbowy w Skarżysku Kamiennej',
		342 => 'Urząd Skarbowy w Starachowicach',
		343 => 'Urząd Skarbowy w Staszowie',
		344 => 'Urząd Skarbowy we Włoszczowie',
		345 => 'Izba Skarbowa w Olsztynie',
		346 => 'Warmińsko Mazurski Urząd Skarbowy w Olsztynie',
		347 => 'Urząd Skarbowy w Bartoszycach',
		348 => 'Urząd Skarbowy w Braniewie',
		349 => 'Urząd Skarbowy w Działdowie',
		350 => 'Urząd Skarbowy w Elblągu',
		351 => 'Urząd Skarbowy w Ełku',
		352 => 'Urząd Skarbowy w Giżycku',
		353 => 'Urząd Skarbowy w Iławie',
		354 => 'Urząd Skarbowy w Kętrzynie',
		355 => 'Urząd Skarbowy w Nidzicy',
		356 => 'Urząd Skarbowy w Nowym Mieście Lubawskim',
		357 => 'Urząd Skarbowy w Olecku',
		358 => 'Urząd Skarbowy w Olsztynie',
		359 => 'Urząd Skarbowy w Ostródzie',
		360 => 'Urząd Skarbowy w Piszu',
		361 => 'Urząd Skarbowy w Szczytnie',
		362 => 'Izba Skarbowa w Poznaniu',
		363 => 'Biuro Wymiany Informacji Podatkowych w Koninie',
		364 => 'Biuro Krajowej Informacji Podatkowej w Lesznie',
		365 => 'Pierwszy Wielkopolski Urząd Skarbowy w Poznaniu',
		366 => 'Drugi Wielkopolski Urząd Skarbowy w Kaliszu',
		367 => 'Urząd Skarbowy w Chodzieży',
		368 => 'Urząd Skarbowy w Czarnkowie',
		369 => 'Urząd Skarbowy w Gnieźnie',
		370 => 'Urząd Skarbowy w Gostyniu',
		371 => 'Urząd Skarbowy w Grodzisku Wielkopolskim',
		372 => 'Urząd Skarbowy w Jarocinie',
		373 => 'Pierwszy Urząd Skarbowy w Kaliszu',
		374 => 'Drugi Urząd Skarbowy w Kaliszu',
		375 => 'Urząd Skarbowy w Kępnie',
		376 => 'Urząd Skarbowy w Kole',
		377 => 'Urząd Skarbowy w Koninie',
		378 => 'Urząd Skarbowy w Kościanie',
		379 => 'Urząd Skarbowy w Krotoszynie',
		380 => 'Urząd Skarbowy w Lesznie',
		381 => 'Urząd Skarbowy w Międzychodzie',
		382 => 'Urząd Skarbowy w Nowym Tomyślu',
		383 => 'Urząd Skarbowy w Obornikach Wlkp.',
		384 => 'Urząd Skarbowy w Ostrowie Wielkopolskim',
		385 => 'Urząd Skarbowy w Ostrzeszowie',
		386 => 'Urząd Skarbowy w Pile',
		387 => 'Urząd Skarbowy w Pleszewie',
		388 => 'Urząd Skarbowy Poznań-Grunwald',
		389 => 'Urząd Skarbowy Poznań-Jeżyce',
		390 => 'Urząd Skarbowy Poznań-Nowe Miasto',
		391 => 'I Urząd Skarbowy w Poznaniu',
		392 => 'Urząd Skarbowy Poznań-Winogrady',
		393 => 'Urząd Skarbowy Poznań-Wilda',
		394 => 'Urząd Skarbowy w Rawiczu',
		395 => 'Urząd Skarbowy w Słupcy',
		396 => 'Urząd Skarbowy w Szamotułach',
		397 => 'Urząd Skarbowy w Śremie',
		398 => 'Urząd Skarbowy w Środzie Wielkoposkiej',
		399 => 'Urząd Skarbowy w Turku',
		400 => 'Urząd Skarbowy w Wągrowcu',
		401 => 'Urząd Skarbowy w Wolsztynie',
		402 => 'Urząd Skarbowy we Wrześni',
		403 => 'Urząd Skarbowy w Złotowie',
		404 => 'Izba Skarbowa w Szczecinie',
		405 => 'Zachodniopomorski Urząd Skarbowy w Szczecinie',
		406 => 'Urząd Skarbowy w Białogardzie',
		407 => 'Urząd Skarbowy w Choszcznie',
		408 => 'Urząd Skarbowy w Drawsku Pomorskim',
		409 => 'Urząd Skarbowy w Goleniowie',
		410 => 'Urząd Skarbowy w Gryficach',
		411 => 'Urząd Skarbowy w Gryfinie',
		412 => 'Urząd Skarbowy w Kamieniu Pomorskim',
		413 => 'Urząd Skarbowy w Kołobrzegu',
		414 => 'Pierwszy Urząd Skarbowy w Koszalinie',
		415 => 'Drugi Urząd Skarbowy w Koszalinie',
		416 => 'Urząd Skarbowy w Myśliborzu',
		417 => 'Urząd Skarbowy w Pyrzycach',
		418 => 'Urząd Skarbowy w Stargardzie Szczecińskim',
		419 => 'Pierwszy Urząd Skarbowy w Szczecinie',
		420 => 'Drugi Urząd Skarbowy w Szczecinie',
		421 => 'Trzeci Urząd Skarbowy w Szczecinie',
		422 => 'Urząd Skarbowy w Szczecinku',
		423 => 'Urząd Skarbowy w Świnoujściu',
		424 => 'Urząd Skarbowy w Wałczu'
	)
);
?>